### ISSUE TITLE
论文的结果不能复现

### ISSUE THREAD

**Issue by qwertyuiopasdfghjklzxcn** [csj199813/A2Net_ECPE#3]
我按照readme的步骤运行代码，十折交叉验证的平均结果为：
情感原因配对抽取：P=0.6765，R=0.6994，F=0.6871
情感抽取：P=0.8482，R=0.8445，F=0.8459
原因抽取：P=0.7153，R=0.7243，F=0.7191

与论文报道结果有较大的差距

**Comment by csj199813** [comment]
请确保运行实验环境与论文一致：
CUDA：11.4
Python 3
PyTorch 1.10.2
The code has been tested on Ubuntu 20.04.3 LTS using a single 3090(24G).
